services:
  api_host: "localhost"
  api_base_path: "/nomad-oasis"

oasis:
  is_oasis: true
  uses_central_user_management: true

north:
  jupyterhub_crypt_key: "978bfb2e13a8448a253c629d8dd84ff89587f30e635b753153960930cad9d36d"
  tools:
    options:
      jupyter:
        image: ghcr.io/mxwalbert/ait-echt-oasis/jupyter:main

meta:
  deployment: 'ait-echt-oasis'
  deployment_url: 'localhost/api'
  maintainer_email: 'echt-oasis@ait.ac.at'

logstash:
  enabled: false

mongo:
  db_name: nomad_oasis_v1

elastic:
  entries_index: nomad_oasis_entries_v1
  materials_index: nomad_oasis_materials_v1

plugins:
  entry_points:
    exclude:
      - apps/2_theory/1_calculations
      - apps/2_theory/2_materials
      - apps/3_experiment/2_eels
      - pynxtools.nomad.entrypoints:nexus_app
      - example_uploads/1_basic_examples/1_theory
      - example_uploads/1_basic_examples/2_eln
      - example_uploads/1_basic_examples/3_tables
      - example_uploads/2_tutorials/1_rdm_tutorial
      - example_uploads/2_tutorials/2_cow_tutorial
      - pynxtools.nomad.entrypoints:simple_nexus_example
